export enum ERROR_CODE {
    //General Errors & Internal Server Error
    OPERATION_FAILURE,
    AUTH_FAILURE,
    DB_FAILURE,
    VALIDATION_ERROR,
    UNKNOWN_ERROR,
    NOT_FOUND,
    INVALID_JSON,

    //Tenant Sign Up
    DOMAIN_ALREADY_EXIST,
    TENANT_ALREADY_EXIST,
    TENANT_NOT_CREATED,
    NOT_AUTHENTICATED_USER,
    TENANT_INVALID,
    INVALID_TOKEN,

    //Category
    CATEGORY_NOT_FOUND,
    CATEGORY_TITLE_INVALID,

    //Brand
    BRAND_NAME_INVALID,
    BRAND_NOT_FOUND,

    //TaxBracket
    TAX_BRACKET_NAME_INVALID,
    TAX_GROUP_INVALID_BRACKET,
    TAX_BRACKET_INVALID,

    //Stock Unit
    STOCK_UNIT_NAME_INVALID,
    STOCK_UNIT_NOT_FOUND,

    //Outlet
    OUTLET_INVALID_OUTLET,
    OUTLET_NAME_INVALID,

    //Product
    PRODUCT_NOT_FOUND,

    // plugin
    PLUGIN_INVALID,
    PLUGIN_ALREADY_INSTALLED,

    //Inventory
    INVENTORY_PRODUCT_NOT_IN_CATALOGUE,
    INVENTORY_PRODUCT_NOT_IN_INVENTORY,
}
